#!/bin/bash
set -e
set -x

ACTIVITI_ADMIN_USER_REV=${ACTIVITI_ADMIN_USER_REV:-2}
ACTIVITI_ADMIN_USER_FIRSTNAME=${ACTIVITI_ADMIN_USER_FIRSTNAME:-Administrator}
ACTIVITI_ADMIN_USER_LASTNAME=${ACTIVITI_ADMIN_USER_LASTNAME:-Activiti}
ACTIVITI_ADMIN_USER_EMAIL=${ACTIVITI_ADMIN_USER_EMAIL:-admin@activiti.org}
ACTIVITI_ADMIN_USER_PASSWORD=${ACTIVITI_ADMIN_USER_PASSWORD:-admin}
ACTIVITI_ADMIN_USER_PICTUREID=${ACTIVITI_ADMIN_USER_PICTUREID:-admin}

# Configure tomcat admin user/password
TOMCAT_ADMIN_USER=${TOMCAT_ADMIN_USER:-admin}
TOMCAT_ADMIN_PASSWORD=${TOMCAT_ADMIN_PASSWORD:-admin}
cat <<EOF > /opt/tomcat/conf/tomcat-users.xml
<?xml version='1.0' encoding='utf-8'?>
<tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">
  <role rolename="admin-gui"/>
  <role rolename="admin-script"/>
  <role rolename="manager-gui"/>
  <role rolename="manager-status"/>
  <role rolename="manager-script"/>
  <role rolename="manager-jmx"/>
  <user name="${TOMCAT_ADMIN_USER}" password="${TOMCAT_ADMIN_PASSWORD}" roles="admin-gui,admin-script,manager-gui,manager-status,manager-script,manager-jmx"/>
</tomcat-users>
EOF

#Check if proper DB environment variables are set
if [[ ! -v ACTIVITI_DB_HOST || ! -v ACTIVITI_DB_USER || ! -v ACTIVITI_DB_PASSWORD ]]
then
printf "\nDatabase Environment variables not set. Cannot find database, exiting....\n\n"
exit 1
fi
#Create .my.cnf file for easy database access
cat <<EOF > ~/.my.cnf
[client]
host=${ACTIVITI_DB_HOST}
user=${ACTIVITI_DB_USER}
password=${ACTIVITI_DB_PASSWORD}
EOF

#Create the db.properties
cat <<EOF > /opt/tomcat/webapps/activiti-explorer/WEB-INF/classes/db.properties
jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://${ACTIVIT_DB_HOST}:3306/${ACTIVIT_DB_NAME}?autoReconnect=true&characterEncoding=utf8
jdbc.username=${ACTIVIT_DB_USER}
jdbc.password=${ACTIVIT_DB_PASSWORD}
db=mysql
EOF
cat <<EOF > /opt/tomcat/webapps/activiti-rest/WEB-INF/classes/db.properties
jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://${ACTIVIT_DB_HOST}:3306/${ACTIVIT_DB_NAME}?autoReconnect=true&characterEncoding=utf8
jdbc.username=${ACTIVIT_DB_USER}
jdbc.password=${ACTIVIT_DB_PASSWORD}
db=mysql
EOF

#Test if Database exists and also if its empty
if ! mysql ${ACTIVITI_DB_NAME} -e "SHOW TABLES"
then
printf "\nDatabase donot exist.. Trying to create \n\n"
mysqladmin create ${ACTIVITI_DB_NAME} || exit 2
fi

TABLE_COUNT_COMMAND="SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '${ACTIVITI_DB_NAME}'"
if [[ $(mysql -e "$TABLE_COUNT_COMMAND" | tail -1) -eq 0 ]]
then
printf "\nDatabase is empty, trying to create Activiti Tables\n\n"
chmod +x /opt/tomcat/bin/catalina.sh
/opt/tomcat/bin/catalina.sh start
sleep 15
/opt/tomcat/bin/catalina.sh stop
fi

#Create Admin User for activiti
printf "Creating Admin User for Activiti...\n"
mysql -e "INSERT INTO ${ACTIVITI_DB_NAME}.ACT_ID_USER (ID_,REV_,FIRST_,LAST_,EMAIL_,PWD_,PICTURE_ID_)
VALUES ('${ACTIVITI_DB_NAME}',${ACTIVITI_ADMIN_USER_REV},'${ACTIVITI_ADMIN_USER_FIRSTNAME}','${ACTIVITI_ADMIN_USER_LASTNAME}','${ACTIVITI_ADMIN_USER_EMAIL}','${ACTIVITI_ADMIN_USER_PASSWORD}',${ACTIVITI_ADMIN_USER_PICTUREID})"

/opt/tomcat/bin/catalina.sh run
